# Generated by Django 2.2.2 on 2019-10-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='parents_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_name',
            field=models.CharField(default='none', max_length=60),
        ),
    ]
