# Generated by Django 2.2.2 on 2019-10-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191007_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
