# Generated by Django 2.2.2 on 2019-10-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191009_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='student_name',
            field=models.CharField(choices=[('Pa', 'Parent'), ('St', 'Staff')], default='Pa', max_length=2),
        ),
    ]
