# Generated by Django 2.2.2 on 2019-10-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191010_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='student_name',
            field=models.CharField(default='none', max_length=60),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_status',
            field=models.CharField(choices=[('Pa', 'Parent'), ('St', 'Staff')], default='Pa', max_length=2),
        ),
    ]
