# Generated by Django 2.2.2 on 2019-10-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191010_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_status',
            new_name='user_type',
        ),
    ]
