# Generated by Django 2.2.2 on 2019-10-10 12:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circular_feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=20)),
                ('created_for', models.CharField(default='staff', max_length=20)),
                ('message', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('circular_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circular_feed.Circular')),
            ],
        ),
        migrations.CreateModel(
            name='MessageStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Waiting for response', 'Waiting for response'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('last_message', models.TextField()),
                ('last_message_time', models.DateTimeField(default=datetime.datetime.now)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('circular_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circular_feed.Circular')),
            ],
            options={
                'unique_together': {('circular_id', 'created_by')},
            },
        ),
    ]
