# Generated by Django 2.2.2 on 2019-09-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation_interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compose',
            name='receiver',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
