# Generated by Django 2.2.2 on 2019-10-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation_interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created_by_staff_username',
            field=models.CharField(default='admin', max_length=20),
        ),
    ]
