# Generated by Django 2.2.2 on 2019-09-28 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation_interface', '0002_compose_receiver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compose',
            old_name='post',
            new_name='circular_id',
        ),
    ]
